import type { Persona } from "@/types/core";

export const PERSONAS: Persona[] = [
  {
    id: "method_actor",
    subsystem: "film",
    kind: "regular",
    title: "方法派",
    subtitle: "嘴上克制，声音已经入戏",
    center: { contrast: 70, drama: 52, z1: 60, z2: 55, z3: 55 },
    cardCopy: "你的声音最擅长把平静台词演出暗流，像随时准备进入下一场戏。",
    image: { src: "/personas/vbti/02_method_actor.png", themeColor: "#7B4B3A" },
  },
  {
    id: "villain_specialist",
    subsystem: "film",
    kind: "regular",
    title: "反派专业户",
    subtitle: "压着火说话，越压越有戏",
    center: { contrast: 82, drama: 62, z1: 50, z2: 65, z3: 45 },
    cardCopy: "你的反差不是露馅，是镜头特写。越平静，越像在憋一段狠台词。",
    image: { src: "/personas/vbti/03_villain_specialist.png", themeColor: "#5B2A36" },
  },
  {
    id: "oscar_best_actor",
    subsystem: "film",
    kind: "rare",
    title: "奥斯卡影帝",
    subtitle: "声线和文本分头飙戏",
    rules: [{ id: "oscar_split", label: "超高反差中高抓马", when: { contrast: { min: 82 }, drama: { min: 55 } } }],
    cardCopy: "系统听见了两套剧本：你说的是一版，声音偷偷演的是另一版。",
    image: { src: "/personas/vbti/05_oscar_best_actor.png", themeColor: "#B88A44" },
  },
  {
    id: "standup_performer",
    subsystem: "variety",
    kind: "regular",
    title: "脱口秀选手",
    subtitle: "包袱还没说完，节奏先起飞",
    center: { contrast: 55, drama: 88, z1: 24, z2: 65, z3: 30 },
    cardCopy: "你的声音自带上场感，停顿、重启和峰值都像在等观众接梗。",
    image: { src: "/personas/vbti/09_standup_performer.png", themeColor: "#D7263D" },
  },
  {
    id: "atmosphere_driver",
    subsystem: "variety",
    kind: "regular",
    title: "氛围担当",
    subtitle: "每句话都想把场子热起来",
    center: { contrast: 45, drama: 78, z1: 35, z2: 58, z3: 35 },
    cardCopy: "你不一定最吵，但你很会把声音递到人群中间，让气氛自己亮起来。",
    image: { src: "/personas/vbti/10_atmosphere_driver.png", themeColor: "#F28C38" },
  },
  {
    id: "variety_ramblings",
    subsystem: "variety",
    kind: "fallback",
    title: "综艺废话文学",
    subtitle: "抓马有余，剧情随机",
    rules: [{ id: "high_drama_general", label: "高抓马泛化兜底", when: { drama: { min: 70 } } }],
    cardCopy: "你的声学戏份已经够了，内容负责自由发挥，综艺效果负责自己长出来。",
    image: { src: "/personas/vbti/13_variety_ramblings.png", themeColor: "#F6BD60" },
  },
  {
    id: "poet_reader",
    subsystem: "stage",
    kind: "regular",
    title: "朗诵艺术家",
    subtitle: "停顿像幕布，句子像追光",
    center: { contrast: 25, drama: 72, z1: 88, z2: 58, z3: 92 },
    cardCopy: "你的声音懂得留白，句子一拉长，就像站上了舞台中央。",
    image: { src: "/personas/vbti/17_poet_reader.png", themeColor: "#8A5A9A" },
  },
  {
    id: "monologue_maniac",
    subsystem: "stage",
    kind: "regular",
    title: "独白狂魔",
    subtitle: "越讲越像一场内心戏",
    center: { contrast: 32, drama: 82, z1: 82, z2: 66, z3: 96 },
    cardCopy: "你说话有一种自带长镜头的倾向，越往后越像在完成一段独白。",
    image: { src: "/personas/vbti/16_monologue_maniac.png", themeColor: "#4D6A8A" },
  },
  {
    id: "veteran_actor",
    subsystem: "stage",
    kind: "rare",
    title: "老戏骨",
    subtitle: "稳、长、准，台词自己站住",
    rules: [{ id: "stage_master", label: "高稳定高独白", when: { z1: { min: 88 }, z3: { min: 88 }, drama: { min: 65 } } }],
    cardCopy: "你的戏不靠猛冲，靠稳定地把每个字按在舞台地板上。",
    image: { src: "/personas/vbti/19_veteran_actor.png", themeColor: "#6B4E71" },
  },
  {
    id: "navigation_announcer",
    subsystem: "robot",
    kind: "regular",
    title: "导航播报员",
    subtitle: "前方三百米，情绪保持直行",
    center: { contrast: 38, drama: 12, z1: 88, z2: 45, z3: 48 },
    cardCopy: "你的声音稳定得像系统提示，情绪不抢戏，信息自己排队通过。",
    image: { src: "/personas/vbti/23_navigation_announcer.png", themeColor: "#4A6FA5" },
  },
  {
    id: "ai_customer_2049",
    subsystem: "robot",
    kind: "regular",
    title: "AI 客服 2049",
    subtitle: "礼貌、稳定、像刚升级完固件",
    center: { contrast: 45, drama: 18, z1: 82, z2: 55, z3: 55 },
    cardCopy: "你有一种奇妙的服务台质感：每句话都像准备生成工单编号。",
    image: { src: "/personas/vbti/22_ai_customer_2049.png", themeColor: "#5F7A85" },
  },
  {
    id: "error_404_announcer",
    subsystem: "robot",
    kind: "fallback",
    title: "404 播报员",
    subtitle: "情绪未找到，音频信号过低",
    rules: [{ id: "too_flat_or_quiet", label: "低抓马低音量兜底", when: { drama: { max: 12 }, z2: { max: 20 } } }],
    cardCopy: "系统努力听了，但你的情绪像网页一样返回了 404。",
    image: { src: "/personas/vbti/27_error_404_announcer.png", themeColor: "#7E8A97" },
  },
  {
    id: "karaoke_king",
    subsystem: "street",
    kind: "regular",
    title: "麦霸",
    subtitle: "音量一开，整条街都算副歌",
    center: { contrast: 20, drama: 92, z1: 28, z2: 95, z3: 22 },
    cardCopy: "你的声音不太会贴墙走，它更像拿着手麦站在人群前面。",
    image: { src: "/personas/vbti/33_karaoke_king.png", themeColor: "#E4572E" },
  },
  {
    id: "street_soul_singer",
    subsystem: "street",
    kind: "regular",
    title: "街头灵魂歌手",
    subtitle: "每个起伏都想被路灯听见",
    center: { contrast: 28, drama: 86, z1: 36, z2: 82, z3: 34 },
    cardCopy: "你的声线有一种外放的即兴感，像把情绪唱给路过的人听。",
    image: { src: "/personas/vbti/29_street_soul_singer.png", themeColor: "#8E5C42" },
  },
  {
    id: "street_busker",
    subsystem: "street",
    kind: "fallback",
    title: "街头卖艺人",
    subtitle: "抓马很足，落点很野",
    rules: [{ id: "street_general", label: "高抓马高音量兜底", when: { drama: { min: 78 }, z2: { min: 70 } } }],
    cardCopy: "你的声音先把摊支起来了，至于今天演哪一出，交给现场发挥。",
    image: { src: "/personas/vbti/31_street_busker.png", themeColor: "#9A6B2F" },
  },
];
